server:
  port: 8010

app:
  character-Encoding: utf8
  use-unicode: true

spring:
  main:
    allow-bean-definition-overriding: true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
  application:
    name: javaserver.api

logging:
  level:
    org:
      springframework.boot.autoconfigure: ERROR
      hibernate: ERROR
    com.couchbase.client.core:
      CouchbaseCore: ERROR
      endpoint.Endpoint: ERROR
      env.CoreEnvironment: ERROR
    springfox: ERROR
    org.springframework.data.repository.config: ERROR
